import React from 'react';
import { useEffect } from 'react';
import SimpleBanner from './SimpleBanner';

const Privacy = (props) => {
    useEffect(() => {
        document.title = `Privacy Policy | WHMCS Digital`;
        props.setProgress(100);
        document.querySelector("header").className = "header_main inner_page";
        window.scrollTo(0, 0)
      }, []);
  return (
    <>
        <SimpleBanner title="WHMCS Digital Privacy Policy" pagetitle="Privacy Policy"/>
        <div className="privacy_text">
            <div className="container">
                <div className="row">
                    <div className="col-12">
                        <div className="privacy_content">
                            <h2>Privacy Policy</h2>
                            <p className="p_style"> Updated at 2021-06-04 </p>
                            <p className="p_style"> WHMCS Digital. We are committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by WHMCS Digital. This Privacy Policy applies to our website, <a href="https://whmcsdigital.com/">https://whmcsdigital.com/</a>                        , and its associated subdomains (collectively, our "Service"). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information
                                as described in this Privacy Policy and our Terms of Service. </p>
                        </div>
                        <div className="privacy_content">
                            <h2>Definitions and key terms</h2>
                            <p className="p_style"> For this Privacy Policy: </p>
                            <ul>
                                <li><span><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br></br></span></li>
                                <li><span><strong>Company:</strong> when this policy mentions “WHMCS Digital” it refers to <a href="https://whmcsdigital.com/">WHMCS Digital</a>, C-196/A, Times Square Building, 3rd Floor, Sector 74, Sahibzada Ajit Singh Nagar, Punjab 160071 that is responsible for your information under this Privacy Policy.<br></br></span></li>
                                <li><span><strong>Country:</strong> where WHMCS Digital or the owners/founders of WHMCS Digital are based, in this case is India.<br></br></span></li>
                                <li><span><strong>Customer:</strong> refers to the company, organization or person that signs up to use the WHMCS Digital Service to manage the relationships with your consumers or service users.<br></br></span></li>
                                <li><span><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit WHMCS Digital and use the services.<br></br></span></li>
                                <li><span><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.<br></br></span></li>
                                <li><span><strong>Personnel:</strong> refers to those individuals who are employed by WHMCS Digital or are under contract to perform a service on behalf of one of the parties.<br></br></span></li>
                                <li><span><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.<br></br></span></li>
                                <li><span><strong>Service:</strong> refers to the service provided by WHMCS Digital as described in the relative terms (if available) and on this platform.<br></br></span></li>
                                <li><span><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.<br></br></span></li>
                                <li><span><strong>Website:</strong> WHMCS Digital’s site, which can be accessed via this URL: <a href="https://whmcsdigital.com/">https://whmcsdigital.com/</a><br></br></span></li>
                                <li><span><strong>You:</strong> a person or entity that is registered with WHMCS Digital to use the Services.<br></br></span></li>
                            </ul>
                        </div>
                        <div className="privacy_content">
                            <h2>What Information Do We Collect?</h2>
                            <p className="p_style"> We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form. </p>
                            <ul className="ul1">
                                <li><strong>Full Name</strong> </li>
                                <li><strong>Phone Numbers</strong> </li>
                                <li><strong>Email Addresses</strong> </li>
                                <li><strong>Password</strong></li>
                            </ul>
                            <p className="p_style">We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
                        </div>
                        <div className="privacy_content">
                            <h2>How Do We Use The Information We Collect?</h2>
                            <p className="p_style"> Any of the information we collect from you may be used in one of the following ways: </p>
                            <ul>
                                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                                <li>To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)</li>
                                <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
                                <li>To process transactions</li>
                                <li>To administer a contest, promotion, survey or other site feature</li>
                                <li>To send periodic emails</li>
                            </ul>
                        </div>
                        <div className="privacy_content">
                            <h2>When do we use customer information from third parties?</h2>
                            <p className="p_style"> We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party that provides automated
                                fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these
                                websites and changing your privacy settings. </p>
                        </div>
                        <div className="privacy_content">
                            <h2>Do we share the information we collect with third parties?</h2>
                            <p className="p_style"> We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services
                                we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer
                                your personal and non-personal information to our successors-in-interest. </p>
                            <p className="p_style"> We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing,
                                credit card processing, customer service and fulfilling orders for products and services you may purchase through our platform. We will likely share your personal information, and possibly some non-personal information, with these
                                third parties to enable them to perform these services for us and for you. </p>
                            <p className="p_style"> We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to
                                estimate general location and other technographics such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service. They may aggregate information about our advertising
                                and what you see on the service and then provide auditing, research and reporting for us and our advertisers. </p>
                            <p className="p_style"> We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal
                                process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply
                                with applicable court orders, laws, rules and regulations. </p>
                        </div>
                        <div className="privacy_content">
                            <h2>Where and when is information collected from customers and end users?</h2>
                            <p className="p_style"> We will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above. </p>
                        </div>
                        <div className="privacy_content">
                            <h2>How Do We Use Your Email Address?</h2>
                            <p className="p_style"> By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included
                                in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By
                                submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications
                                from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through
                                another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
                                </p>
                        </div>
                        <div className="privacy_content">
                            <h2>Tracking Technologies</h2>
                            <p className="p_style"> Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information
                                stored in the HTTP request header. </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </>
  );
};

export default Privacy;
