const Allcards = [
    {
      id: 1,
      image: "icon-responsive",
      title: "WHMCS Modules Development and Automation",
      description: "Grow y	usiness by letting us automate your WHMCS functionality with our WHMCS modules development and automation services.",
      readmorelink: "whmcs-modules-development",
      price: "$69.95/yr",
      review: "5",
      category: "domain",
    },
    {
      id: 2,
      image: "icon-timeline",
      title: "WHMCS Custom Theme Development",
      description: "Leverage our years of experience by offering a user-friendly and impressive look to your client area with our WHMCS custom theme development solutions.",
      readmorelink: "whmcs-custom-theme-development",
      price: "$59.95/yr",
      review: "4",
      category: "Payment",
    },
    {
      id: 3,
      image: "icon-maintenance",
      title: "3rd Party Tool/APIs integration",
      description: "Our professionals are well-experienced in customizing the payment gateway integration or other API integrations into your WHMCS.",
      readmorelink: "whmcs-modules-development",
      price: "$49.95/yr",
      review: "5",
      category: "",
    },
    {
      id: 4,
      image: "icon-consultant",
      title: "Server Administration",
      description: "Server administration is our another great expertise. FTP (and SSH) access to your WHMCS server – is all we need!",
      readmorelink: "server-management-services",
      price: "$29.95/yr",
      review: "5",
      category: "",
    },
    {
      id: 5,
      image: "icon-consultant",
      title: "WHMCS Setup Version upgrade and Configuration",
      description: "From setting up WHMCS to upgrading to the latest versions to WHMCS configuration, we do everything for you!",
      readmorelink: "whmcs-setup",
      price: "$89.95/yr",
      review: "3",
      category: "",
    },
    {
      id: 6,
      image: "icon-to-do",
      title: "Customization Development",
      description: "Get best-in-class customized WHMCS themes and modules within your required timeline and cost-effective budget.",
      readmorelink: "whmcs-customization",
      price: "$82.95/yr",
      review: "5",
      category: "",
    },
    {
      id: 7,
      image: "icon-responsive",
      title: "Customization Development",
      description: "Get best-in-class customized WHMCS themes and modules within your required timeline and cost-effective budget.",
      readmorelink: "whmcs-customization",
      price: "$52.95/yr",
      review: "4",
      category: "",
    },
    {
      id: 8,
      image: "icon-responsive",
      title: "Customization Development",
      description: "Get best-in-class customized WHMCS themes and modules within your required timeline and cost-effective budget.",
      readmorelink: "whmcs-customization",
      price: "$52.95/yr",
      review: "4",
      category: "",
    },

  ];
  
  export default Allcards;